#!/bin/bash

echo "📦 Preparing to deploy LeadStick Dashboard to Cloudflare Pages..."
echo ""
echo "Since automated deployment is having issues, please follow these steps:"
echo ""
echo "1. Go to your Cloudflare Dashboard: https://dash.cloudflare.com"
echo "2. Navigate to Pages > leadstick-dashboard"
echo "3. Click 'Create deployment'"
echo "4. Upload the 'admin' folder contents"
echo "5. Click 'Deploy'"
echo ""
echo "The dashboard.html file has been updated with:"
echo "- New Email Subject Line field in the form"
echo "- Support for dynamic variables: {service}, {location}, {name}, {phone}"
echo "- The field will save to the config and be used in email notifications"
echo ""
echo "Files to upload:"
echo "- admin/index.html"
echo "- admin/dashboard.html"
echo "- admin/_routes.json"
echo ""
read -p "Press Enter when you've completed the manual deployment..."
echo "✅ Dashboard deployment complete!"