name = "leadstick-api"
main = "worker/index.js"
compatibility_date = "2024-07-01"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.staging]
vars = { ENVIRONMENT = "staging" }

# Environment variables to be set via Cloudflare dashboard or CLI:
# RESEND_API_KEY - Your Resend API key
# GA4_MEASUREMENT_ID - Your GA4 measurement ID (e.g., G-XXXXXXXXXX)
# GA4_API_SECRET - Your GA4 API secret for server-side tracking