name = "leadstick-api"
main = "worker/index.js"
compatibility_date = "2024-07-01"

# Environment variables (non-sensitive only)
[vars]
ENVIRONMENT = "development"
LEAD_EMAIL_RECIPIENT = "michael.costin@localdigital.com.au"
LEAD_EMAIL_FROM = "LeadStick <hello@coscorp.com.au>"

# Staging environment
[env.staging]
name = "leadstick-api-staging"
[env.staging.vars]
ENVIRONMENT = "staging"
LEAD_EMAIL_RECIPIENT = "leads@quickservicepro.com"
LEAD_EMAIL_FROM = "LeadStick <noreply@leadstick.com>"

# Production environment
[env.production]
name = "leadstick-api-production"
[env.production.vars]
ENVIRONMENT = "production"
LEAD_EMAIL_RECIPIENT = "michael.costin@localdigital.com.au"
LEAD_EMAIL_FROM = "LeadStick <hello@coscorp.com.au>"

# KV Namespaces
[[kv_namespaces]]
binding = "LEADSTICK_CONFIGS"
id = "9ed0226c090542429677c61665c4ebc2"

# Secrets are managed via CLI:
# wrangler secret put RESEND_API_KEY
# wrangler secret put GA4_MEASUREMENT_ID
# wrangler secret put GA4_API_SECRET